spring:
  application:
    name: gateway-server
  profiles:    active:    - dev  
  config:    import: optional:configserver:http://localhost:8888   
  
---

spring:
  application:
    name: gateway-server
  profiles:
    active:
    - prod
  cloud:    config:      profile: prod    
  config:
    import: optional:configserver:http://${CONFIG_SERVER}:8888